/* The following code was generated by JFlex 1.4.3 on 26/6/24 11:04 */

package dev.fmartinez.analizadorlexicojflexfx;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 26/6/24 11:04 from the specification file
 * <tt>E:/sandbox/integrador-computacion/analizador-lexico-Jflex-fx/src/main/java/dev/fmartinez/analizadorlexicojflexfx/Lexex.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\27\2\0\1\3\22\0\1\3\7\0\1\33\1\34"+
    "\1\31\1\31\1\3\1\32\1\0\1\26\12\2\1\36\1\35\1\0"+
    "\1\30\3\0\32\1\4\0\1\1\1\0\1\10\1\14\1\24\1\25"+
    "\1\16\1\22\1\7\1\1\1\13\2\1\1\15\1\11\1\20\1\6"+
    "\1\4\1\1\1\5\1\17\1\21\1\23\1\12\4\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\10\1\1\4\1\5\1\4"+
    "\1\6\1\7\1\10\1\11\7\1\1\12\2\1\1\3"+
    "\1\0\1\13\10\1\1\14\1\1\1\0\4\1\1\15"+
    "\3\1\1\16\1\1\1\2\11\1\1\17\1\1\1\20"+
    "\2\1\1\21\5\1\1\22\1\23\1\1\1\24\1\25"+
    "\1\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\37\0\76\0\135\0\174\0\233\0\272\0\331"+
    "\0\370\0\u0117\0\u0136\0\u0155\0\u0174\0\u0193\0\u0193\0\u01b2"+
    "\0\u0193\0\u0193\0\u01d1\0\u01f0\0\u020f\0\u022e\0\u024d\0\u026c"+
    "\0\u028b\0\u02aa\0\u02c9\0\u02e8\0\u0307\0\u0326\0\u0345\0\u0193"+
    "\0\u0364\0\u0383\0\u03a2\0\u03c1\0\u03e0\0\u03ff\0\u041e\0\u043d"+
    "\0\37\0\u045c\0\u047b\0\u049a\0\u04b9\0\u04d8\0\u04f7\0\37"+
    "\0\u0516\0\u0535\0\u0554\0\37\0\u0573\0\u0193\0\u0592\0\u05b1"+
    "\0\u05d0\0\u05ef\0\u060e\0\u062d\0\u064c\0\u066b\0\u068a\0\37"+
    "\0\u06a9\0\37\0\u06c8\0\u06e7\0\37\0\u0706\0\u0725\0\u0744"+
    "\0\u0763\0\u0782\0\37\0\37\0\u07a1\0\37\0\37\0\37";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\5\4\2\1\6\1\7"+
    "\1\10\1\2\1\11\1\12\1\13\2\2\1\14\3\2"+
    "\1\15\1\4\1\16\2\17\1\20\1\21\1\22\1\23"+
    "\1\0\2\2\1\0\22\2\13\0\1\3\37\0\1\4"+
    "\23\0\1\4\10\0\2\2\1\0\1\2\1\24\20\2"+
    "\12\0\2\2\1\0\2\2\1\25\17\2\12\0\2\2"+
    "\1\0\4\2\1\26\15\2\12\0\2\2\1\0\14\2"+
    "\1\27\5\2\12\0\2\2\1\0\12\2\1\30\7\2"+
    "\12\0\2\2\1\0\13\2\1\31\1\32\5\2\12\0"+
    "\2\2\1\0\7\2\1\33\12\2\12\0\2\2\1\0"+
    "\7\2\1\34\7\2\1\35\2\2\37\0\1\36\101\0"+
    "\1\37\34\0\1\40\7\0\2\2\1\0\2\2\1\41"+
    "\17\2\12\0\2\2\1\0\21\2\1\42\12\0\2\2"+
    "\1\0\1\2\1\43\20\2\12\0\2\2\1\0\7\2"+
    "\1\44\12\2\12\0\2\2\1\0\12\2\1\45\7\2"+
    "\12\0\2\2\1\0\20\2\1\46\1\2\12\0\2\2"+
    "\1\0\15\2\1\47\4\2\12\0\2\2\1\0\14\2"+
    "\1\50\5\2\12\0\2\2\1\0\14\2\1\51\5\2"+
    "\12\0\2\2\1\0\14\2\1\52\5\2\11\0\27\36"+
    "\1\0\7\36\2\0\1\53\35\0\2\2\1\0\3\2"+
    "\1\54\16\2\12\0\2\2\1\0\17\2\1\55\2\2"+
    "\12\0\2\2\1\0\7\2\1\56\12\2\12\0\2\2"+
    "\1\0\20\2\1\57\1\2\12\0\2\2\1\0\1\2"+
    "\1\60\20\2\12\0\2\2\1\0\1\2\1\61\20\2"+
    "\12\0\2\2\1\0\2\2\1\62\7\2\1\63\7\2"+
    "\12\0\2\2\1\0\2\2\1\64\17\2\12\0\2\2"+
    "\1\0\20\2\1\65\1\2\13\0\1\53\31\0\1\66"+
    "\3\0\2\2\1\0\1\2\1\67\20\2\12\0\2\2"+
    "\1\0\11\2\1\70\10\2\12\0\2\2\1\0\4\2"+
    "\1\71\15\2\12\0\2\2\1\0\7\2\1\72\12\2"+
    "\12\0\2\2\1\0\7\2\1\73\12\2\12\0\2\2"+
    "\1\0\14\2\1\74\5\2\12\0\2\2\1\0\1\2"+
    "\1\75\20\2\12\0\2\2\1\0\7\2\1\76\12\2"+
    "\12\0\2\2\1\0\4\2\1\77\15\2\12\0\2\2"+
    "\1\0\2\2\1\100\17\2\12\0\2\2\1\0\10\2"+
    "\1\101\11\2\12\0\2\2\1\0\2\2\1\102\17\2"+
    "\12\0\2\2\1\0\10\2\1\103\11\2\12\0\2\2"+
    "\1\0\20\2\1\104\1\2\12\0\2\2\1\0\2\2"+
    "\1\105\17\2\12\0\2\2\1\0\2\2\1\106\17\2"+
    "\12\0\2\2\1\0\5\2\1\107\14\2\12\0\2\2"+
    "\1\0\11\2\1\110\10\2\12\0\2\2\1\0\7\2"+
    "\1\111\12\2\12\0\2\2\1\0\12\2\1\112\7\2"+
    "\12\0\2\2\1\0\14\2\1\113\5\2\12\0\2\2"+
    "\1\0\4\2\1\114\15\2\12\0\2\2\1\0\12\2"+
    "\1\115\7\2\12\0\2\2\1\0\1\2\1\116\20\2"+
    "\12\0\2\2\1\0\13\2\1\117\6\2\12\0\2\2"+
    "\1\0\13\2\1\120\6\2\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1984];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\14\1\2\11\1\1\2\11\14\1\1\0\1\11"+
    "\12\1\1\0\12\1\1\11\32\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 98) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { lexeme = yytext(); return Tokens.COMPARAR;
          }
        case 23: break;
        case 22: 
          { lexeme = yytext(); return Tokens.VARIABLES;
          }
        case 24: break;
        case 2: 
          { lexeme = yytext(); return Tokens.NUMERO;
          }
        case 25: break;
        case 17: 
          { lexeme = yytext(); return Tokens.ENTERO;
          }
        case 26: break;
        case 11: 
          { lexeme = yytext(); return Tokens.ASIGNACION_VALOR;
          }
        case 27: break;
        case 6: 
          { lexeme = yytext(); return Tokens.PARENTESIS_ABIERTO;
          }
        case 28: break;
        case 19: 
          { lexeme = yytext(); return Tokens.PROGRAMA;
          }
        case 29: break;
        case 9: 
          { lexeme = yytext(); return Tokens.ASIGNACION_VARIABLE;
          }
        case 30: break;
        case 10: 
          { lexeme = yytext(); return Tokens.SI;
          }
        case 31: break;
        case 8: 
          { lexeme = yytext(); return Tokens.FIN_LINEA;
          }
        case 32: break;
        case 20: 
          { lexeme = yytext(); return Tokens.ESCRIBIR;
          }
        case 33: break;
        case 4: 
          { lexeme = yytext(); return Tokens.SIMBOLO_ESPECIAL;
          }
        case 34: break;
        case 7: 
          { lexeme = yytext(); return Tokens.PARENTESIS_CERRADO;
          }
        case 35: break;
        case 14: 
          { lexeme = yytext(); return Tokens.SINO;
          }
        case 36: break;
        case 1: 
          { lexeme = yytext(); return Tokens.IDENTIFICADOR;
          }
        case 37: break;
        case 13: 
          { lexeme = yytext(); return Tokens.LEER;
          }
        case 38: break;
        case 15: 
          { lexeme = yytext(); return Tokens.MODULO;
          }
        case 39: break;
        case 21: 
          { lexeme = yytext(); return Tokens.ENTONCES;
          }
        case 40: break;
        case 3: 
          { /*Ignore*/
          }
        case 41: break;
        case 18: 
          { lexeme = yytext(); return Tokens.FUNCION;
          }
        case 42: break;
        case 16: 
          { lexeme = yytext(); return Tokens.INICIO;
          }
        case 43: break;
        case 12: 
          { lexeme = yytext(); return Tokens.FIN;
          }
        case 44: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
